### ISSUE TITLE
Why does aurora.Gray() take 2 args

### ISSUE THREAD

**Issue by ORESoftware** [logrusorgru/aurora#15]
This is confusing:

<kbd>
<img width="765" alt="Screen Shot 2020-02-07 at 10 27 50 AM" src="https://user-images.githubusercontent.com/11139560/74055314-a296ca00-4994-11ea-93bf-ef5567087689.png">
</kbd>

**Comment by logrusorgru** [comment]
Hi. Because, it's about grayscale in range [0, 23]. Short words

```go
Gray(0, "black")
Gray(23, "white")
```
And the same for `BgGray`.

Doc.: https://github.com/logrusorgru/aurora#grayscale
Ref.: https://en.wikipedia.org/wiki/ANSI_escape_code#8-bit (the "232-255:  grayscale from black to white in 24 steps" line)

---

Any suggestions are welcome.

**Comment by ORESoftware** [comment]
Yeah I would have done:


```
aurora.Gray("this is gray")  // defaults to like 12
aurora.GrayWithScale(16, "this is grayer/whiter")
```

too late though unless you want to introduce a breaking change

**Comment by logrusorgru** [comment]
> to introduce a breaking change

Yeah, no problems with breaking changes, since there is [gopkg.in](https://gopkg.in/) and [go modules](https://blog.golang.org/v2-go-modules). I just want to make some research how to introduce it less painful for users.

Hm, one side is force existing users to rename import path to `<>/v3`, to use new version, other side is force to use `gopkg.in/<>.v2` to use existing version. No elegant solutions....

The `<>/v3` is not elegant, because a potential `v4` will require all imports renaming again. But,

> Stability sucks, I know.

https://github.com/golang/go/issues/9424#issuecomment-67912845

**Comment by logrusorgru** [comment]
Hm, other side

> Previous Gray and BgGray methods are now called White and BgWhite following specification.

**Comment by logrusorgru** [comment]
Actually, the ANSI-colors doesn't have a gray color. The White may return gray depending on terminal settings.

**Comment by logrusorgru** [comment]
So, I reject it, regarding ANSI-colors specification.
